### ISSUE TITLE
[Error] NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.

### ISSUE THREAD

**Issue by Eduardosantosrosa** [platformio/platformio-registry#113]
# Page
https://registry.platformio.org/libraries/arduino-libraries/Ethernet/installation

# Stack
```
at C (https://cdn.registry.platformio.org/static/js/main.625578fb.js:2:504857)
    at M (https://cdn.registry.platformio.org/static/js/main.625578fb.js:2:509605)
    at Suspense
    at div
    at div
    at ee (https://cdn.registry.platformio.org/static/js/main.625578fb.js:2:235281)
    at div
    at main
    at ne (https://cdn.registry.platformio.org/static/js/main.625578fb.js:2:238173)
    at C (https://cdn.registry.platformio.org/static/js/main.625578fb.js:2:504857)
    at L (https://cdn.registry.platformio.org/static/js/main.625578fb.js:2:508906)
    at L (https://cdn.registry.platformio.org/static/js/main.625578fb.js:2:664143)
    at C (https://cdn.registry.platformio.org/static/js/main.625578fb.js:2:504857)
    at M (https://cdn.registry.platformio.org/static/js/main.625578fb.js:2:509605)
    at I (https://cdn.registry.platformio.org/static/js/main.625578fb.js:2:508969)
    at p (https://cdn.registry.platformio.org/static/js/main.625578fb.js:2:497639)
    at https://cdn.registry.platformio.org/static/js/main.625578fb.js:2:614267
    at ml (https://cdn.registry.platformio.org/static/js/main.625578fb.js:2:461645)
    at ml (https://cdn.registry.platformio.org/static/js/main.625578fb.js:2:461645)
```

**Comment by ivankravets** [comment]
Please press Ctrl+R in the browser.
