### ISSUE TITLE
[Error] NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.

### ISSUE THREAD

**Issue by Jalalheysari** [platformio/platformio-registry#17]
# Page
https://registry.platformio.org/libraries/mbed-fwrawx/Rm3100/installation

# Stack
```
at O (https://cdn.registry.platformio.org/static/js/main.2fabc71c.js:2:452211)
    at Suspense
    at div
    at div
    at Q (https://cdn.registry.platformio.org/static/js/main.2fabc71c.js:2:151845)
    at div
    at main
    at Y (https://cdn.registry.platformio.org/static/js/main.2fabc71c.js:2:154619)
    at F (https://cdn.registry.platformio.org/static/js/main.2fabc71c.js:2:451585)
    at P (https://cdn.registry.platformio.org/static/js/main.2fabc71c.js:2:606334)
    at O (https://cdn.registry.platformio.org/static/js/main.2fabc71c.js:2:452211)
    at B (https://cdn.registry.platformio.org/static/js/main.2fabc71c.js:2:451641)
    at b (https://cdn.registry.platformio.org/static/js/main.2fabc71c.js:2:443132)
    at https://cdn.registry.platformio.org/static/js/main.2fabc71c.js:2:557424
    at L (https://cdn.registry.platformio.org/static/js/main.2fabc71c.js:2:605200)
    at I (https://cdn.registry.platformio.org/static/js/main.2fabc71c.js:2:606528)
```

**Comment by ivankravets** [comment]
What is your browser? Could you try to refresh page?

**Comment by ivankravets** [comment]
Please reopen if you still need help
