### ISSUE TITLE
[Error] NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.

### ISSUE THREAD

**Issue by EngenhariaGnatus** [platformio/platformio-registry#21]
# Page
https://registry.platformio.org/libraries/arduino-libraries/GSM/installation

# Stack
```
at O (https://cdn.registry.platformio.org/static/js/main.7cce2b10.js:2:456996)
    at Suspense
    at div
    at div
    at Q (https://cdn.registry.platformio.org/static/js/main.7cce2b10.js:2:152703)
    at div
    at main
    at X (https://cdn.registry.platformio.org/static/js/main.7cce2b10.js:2:155477)
    at F (https://cdn.registry.platformio.org/static/js/main.7cce2b10.js:2:456370)
    at R (https://cdn.registry.platformio.org/static/js/main.7cce2b10.js:2:611100)
    at O (https://cdn.registry.platformio.org/static/js/main.7cce2b10.js:2:456996)
    at B (https://cdn.registry.platformio.org/static/js/main.7cce2b10.js:2:456426)
    at b (https://cdn.registry.platformio.org/static/js/main.7cce2b10.js:2:447917)
    at https://cdn.registry.platformio.org/static/js/main.7cce2b10.js:2:562190
    at hl (https://cdn.registry.platformio.org/static/js/main.7cce2b10.js:2:411438)
    at hl (https://cdn.registry.platformio.org/static/js/main.7cce2b10.js:2:411438)
```

**Comment by ivankravets** [comment]
Could you reproduce this issue after full page reload using Ctrl+R?

**Comment by smb29** [comment]
ok ctrl+r is perfect
