### ISSUE TITLE
[Error] TypeError: Invalid Version: null

### ISSUE THREAD

**Issue by luisr320** [platformio/platformio-registry#37]
# Page
https://registry.platformio.org/libraries/raronoff/clickButton/versions

# Stack
```
at q (https://cdn.registry.platformio.org/static/js/main.7cce2b10.js:2:150318)
    at O (https://cdn.registry.platformio.org/static/js/main.7cce2b10.js:2:456996)
    at Suspense
    at div
    at div
    at Q (https://cdn.registry.platformio.org/static/js/main.7cce2b10.js:2:152703)
    at div
    at main
    at X (https://cdn.registry.platformio.org/static/js/main.7cce2b10.js:2:155477)
    at F (https://cdn.registry.platformio.org/static/js/main.7cce2b10.js:2:456370)
    at R (https://cdn.registry.platformio.org/static/js/main.7cce2b10.js:2:611100)
    at O (https://cdn.registry.platformio.org/static/js/main.7cce2b10.js:2:456996)
    at B (https://cdn.registry.platformio.org/static/js/main.7cce2b10.js:2:456426)
    at b (https://cdn.registry.platformio.org/static/js/main.7cce2b10.js:2:447917)
    at https://cdn.registry.platformio.org/static/js/main.7cce2b10.js:2:562190
    at L (https://cdn.registry.platformio.org/static/js/main.7cce2b10.js:2:609966)
    at I (https://cdn.registry.platformio.org/static/js/main.7cce2b10.js:2:611294)
```

**Comment by ivankravets** [comment]
Please press Ctrl+R and refresh the page. Should be fixed.

**Comment by luisr320** [comment]
Still gives me the same error
![image](https://user-images.githubusercontent.com/20230052/204790788-6e186dbb-6a51-4649-ab7e-844c8a23c8b8.png)

**Comment by ivankravets** [comment]
Thanks! The package was removed from the registry.

**Comment by luisr320** [comment]
Ok, it's showing a 404 now. Shal I close this comment?

**Comment by ivankravets** [comment]
Yes, the package was removed by its owner. Please search in the registry for alternative packages.
