### ISSUE TITLE
[Error] NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.

### ISSUE THREAD

**Issue by AbdouFall2991** [platformio/platformio-registry#44]
# Page
https://registry.platformio.org/libraries/arduino-libraries/WiFi/installation

# Stack
```
at S (https://cdn.registry.platformio.org/static/js/main.6e89eaf9.js:2:472496)
    at I (https://cdn.registry.platformio.org/static/js/main.6e89eaf9.js:2:474464)
    at Suspense
    at div
    at div
    at Q (https://cdn.registry.platformio.org/static/js/main.6e89eaf9.js:2:180992)
    at div
    at main
    at Y (https://cdn.registry.platformio.org/static/js/main.6e89eaf9.js:2:183766)
    at S (https://cdn.registry.platformio.org/static/js/main.6e89eaf9.js:2:472496)
    at R (https://cdn.registry.platformio.org/static/js/main.6e89eaf9.js:2:473816)
    at L (https://cdn.registry.platformio.org/static/js/main.6e89eaf9.js:2:629776)
    at S (https://cdn.registry.platformio.org/static/js/main.6e89eaf9.js:2:472496)
    at I (https://cdn.registry.platformio.org/static/js/main.6e89eaf9.js:2:474464)
    at P (https://cdn.registry.platformio.org/static/js/main.6e89eaf9.js:2:473879)
    at c (https://cdn.registry.platformio.org/static/js/main.6e89eaf9.js:2:466602)
    at https://cdn.registry.platformio.org/static/js/main.6e89eaf9.js:2:580315
    at ml (https://cdn.registry.platformio.org/static/js/main.6e89eaf9.js:2:430998)
    at ml (https://cdn.registry.platformio.org/static/js/main.6e89eaf9.js:2:430998)
```

**Comment by ivankravets** [comment]
Please refresh the page with Ctrl+R. Should be fixed.
