### ISSUE TITLE
[Error] TypeError: Cannot read properties of undefined (reading 'toLowerCase')

### ISSUE THREAD

**Issue by augustas534** [platformio/platformio-registry#45]
# Page
https://registry.platformio.org/libraries/geeksville/esp32-micro-sdcard/examples/nanosdcard

# Stack
```
at D (https://cdn.registry.platformio.org/static/js/main.6e89eaf9.js:2:155589)
    at S (https://cdn.registry.platformio.org/static/js/main.6e89eaf9.js:2:472496)
    at I (https://cdn.registry.platformio.org/static/js/main.6e89eaf9.js:2:474464)
    at Suspense
    at div
    at Q (https://cdn.registry.platformio.org/static/js/main.6e89eaf9.js:2:180992)
    at div
    at main
    at Y (https://cdn.registry.platformio.org/static/js/main.6e89eaf9.js:2:183766)
    at S (https://cdn.registry.platformio.org/static/js/main.6e89eaf9.js:2:472496)
    at R (https://cdn.registry.platformio.org/static/js/main.6e89eaf9.js:2:473816)
    at L (https://cdn.registry.platformio.org/static/js/main.6e89eaf9.js:2:629776)
    at S (https://cdn.registry.platformio.org/static/js/main.6e89eaf9.js:2:472496)
    at I (https://cdn.registry.platformio.org/static/js/main.6e89eaf9.js:2:474464)
    at P (https://cdn.registry.platformio.org/static/js/main.6e89eaf9.js:2:473879)
    at c (https://cdn.registry.platformio.org/static/js/main.6e89eaf9.js:2:466602)
    at https://cdn.registry.platformio.org/static/js/main.6e89eaf9.js:2:580315
    at R (https://cdn.registry.platformio.org/static/js/main.6e89eaf9.js:2:628642)
    at I (https://cdn.registry.platformio.org/static/js/main.6e89eaf9.js:2:629970)
```

**Comment by ivankravets** [comment]
Please refresh the page with Ctrl+R. Should be fixed.
