### ISSUE TITLE
[Error] NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.

### ISSUE THREAD

**Issue by xiaoxiaoguai666** [platformio/platformio-registry#50]
# Page
https://registry.platformio.org/tools/platformio/tool-jlink/installation

# Stack
```
at D (https://cdn.registry.platformio.org/static/js/main.b333717b.js:2:478036)
    at P (https://cdn.registry.platformio.org/static/js/main.b333717b.js:2:480269)
    at Suspense
    at div
    at div
    at ee (https://cdn.registry.platformio.org/static/js/main.b333717b.js:2:185991)
    at div
    at main
    at ne (https://cdn.registry.platformio.org/static/js/main.b333717b.js:2:188883)
    at D (https://cdn.registry.platformio.org/static/js/main.b333717b.js:2:478036)
    at T (https://cdn.registry.platformio.org/static/js/main.b333717b.js:2:479621)
    at L (https://cdn.registry.platformio.org/static/js/main.b333717b.js:2:636844)
    at D (https://cdn.registry.platformio.org/static/js/main.b333717b.js:2:478036)
    at P (https://cdn.registry.platformio.org/static/js/main.b333717b.js:2:480269)
    at L (https://cdn.registry.platformio.org/static/js/main.b333717b.js:2:479684)
    at c (https://cdn.registry.platformio.org/static/js/main.b333717b.js:2:472518)
    at u.defineProperty.value (https://cdn.registry.platformio.org/static/js/main.b333717b.js:2:587499)
    at ml (https://cdn.registry.platformio.org/static/js/main.b333717b.js:2:436914)
    at ml (https://cdn.registry.platformio.org/static/js/main.b333717b.js:2:436914)
```

**Comment by ivankravets** [comment]
Please press Ctrl+R in your browser. Should work now.
