### ISSUE TITLE
[Error] NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.

### ISSUE THREAD

**Issue by mayamaya13** [platformio/platformio-registry#6]
# Page
https://registry.platformio.org/tools/platformio/contrib-piohome/installation

# Stack
```
at h (https://cdn.registry.platformio.org/static/js/main.2eef75c9.js:2:436069)
    at Suspense
    at div
    at div
    at Q (https://cdn.registry.platformio.org/static/js/main.2eef75c9.js:2:150382)
    at div
    at main
    at Y (https://cdn.registry.platformio.org/static/js/main.2eef75c9.js:2:153156)
    at u (https://cdn.registry.platformio.org/static/js/main.2eef75c9.js:2:435443)
    at P (https://cdn.registry.platformio.org/static/js/main.2eef75c9.js:2:594134)
    at h (https://cdn.registry.platformio.org/static/js/main.2eef75c9.js:2:436069)
    at d (https://cdn.registry.platformio.org/static/js/main.2eef75c9.js:2:435499)
    at u (https://cdn.registry.platformio.org/static/js/main.2eef75c9.js:2:433393)
    at https://cdn.registry.platformio.org/static/js/main.2eef75c9.js:2:485124
    at L (https://cdn.registry.platformio.org/static/js/main.2eef75c9.js:2:593000)
    at I (https://cdn.registry.platformio.org/static/js/main.2eef75c9.js:2:594328)
```

**Comment by ivankravets** [comment]
What is your browser? Could you reproduce this issue after a full refresh? Ctr+R / Cmd+R

**Comment by ivankravets** [comment]
Please reopen if you still need help
