### ISSUE TITLE
[Error] TypeError: Cannot read properties of undefined (reading 'items')

### ISSUE THREAD

**Issue by aioue** [platformio/platformio-registry#61]
# Page
https://registry.platformio.org/platforms/platformio/atmelsam/insights/dependencies?p=2

# Stack
```
at P (https://cdn.registry.platformio.org/static/js/main.09fa2426.js:2:164691)
    at I (https://cdn.registry.platformio.org/static/js/main.09fa2426.js:2:165152)
    at D (https://cdn.registry.platformio.org/static/js/main.09fa2426.js:2:477623)
    at P (https://cdn.registry.platformio.org/static/js/main.09fa2426.js:2:480111)
    at Suspense
    at div
    at div
    at U (https://cdn.registry.platformio.org/static/js/main.09fa2426.js:2:166008)
    at D (https://cdn.registry.platformio.org/static/js/main.09fa2426.js:2:477623)
    at P (https://cdn.registry.platformio.org/static/js/main.09fa2426.js:2:480111)
    at Suspense
    at div
    at ee (https://cdn.registry.platformio.org/static/js/main.09fa2426.js:2:187159)
    at div
    at main
    at ne (https://cdn.registry.platformio.org/static/js/main.09fa2426.js:2:190051)
    at D (https://cdn.registry.platformio.org/static/js/main.09fa2426.js:2:477623)
    at T (https://cdn.registry.platformio.org/static/js/main.09fa2426.js:2:479461)
    at L (https://cdn.registry.platformio.org/static/js/main.09fa2426.js:2:638014)
    at D (https://cdn.registry.platformio.org/static/js/main.09fa2426.js:2:477623)
    at P (https://cdn.registry.platformio.org/static/js/main.09fa2426.js:2:480111)
    at L (https://cdn.registry.platformio.org/static/js/main.09fa2426.js:2:479524)
    at c (https://cdn.registry.platformio.org/static/js/main.09fa2426.js:2:471946)
    at c.defineProperty.value (https://cdn.registry.platformio.org/static/js/main.09fa2426.js:2:588263)
    at R (https://cdn.registry.platformio.org/static/js/main.09fa2426.js:2:636880)
    at I (https://cdn.registry.platformio.org/static/js/main.09fa2426.js:2:638208)
```

**Comment by ivankravets** [comment]
Please press Ctrl+R in your web browser.
