### ISSUE TITLE
[Error] TypeError: Cannot read properties of undefined (reading 'items')

### ISSUE THREAD

**Issue by ivopopov** [platformio/platformio-registry#63]
# Page
https://registry.platformio.org/platforms/platformio/atmelsam/insights/dependencies?p=2

# Stack
```
at L (https://cdn.registry.platformio.org/static/js/main.88ce3609.js:2:167575)
    at I (https://cdn.registry.platformio.org/static/js/main.88ce3609.js:2:168036)
    at _ (https://cdn.registry.platformio.org/static/js/main.88ce3609.js:2:482003)
    at T (https://cdn.registry.platformio.org/static/js/main.88ce3609.js:2:484635)
    at Suspense
    at div
    at div
    at U (https://cdn.registry.platformio.org/static/js/main.88ce3609.js:2:168892)
    at _ (https://cdn.registry.platformio.org/static/js/main.88ce3609.js:2:482003)
    at T (https://cdn.registry.platformio.org/static/js/main.88ce3609.js:2:484635)
    at Suspense
    at div
    at ee (https://cdn.registry.platformio.org/static/js/main.88ce3609.js:2:190098)
    at div
    at main
    at ne (https://cdn.registry.platformio.org/static/js/main.88ce3609.js:2:192990)
    at _ (https://cdn.registry.platformio.org/static/js/main.88ce3609.js:2:482003)
    at F (https://cdn.registry.platformio.org/static/js/main.88ce3609.js:2:483985)
    at P (https://cdn.registry.platformio.org/static/js/main.88ce3609.js:2:641148)
    at _ (https://cdn.registry.platformio.org/static/js/main.88ce3609.js:2:482003)
    at T (https://cdn.registry.platformio.org/static/js/main.88ce3609.js:2:484635)
    at B (https://cdn.registry.platformio.org/static/js/main.88ce3609.js:2:484048)
    at c (https://cdn.registry.platformio.org/static/js/main.88ce3609.js:2:475312)
    at c.defineProperty.value (https://cdn.registry.platformio.org/static/js/main.88ce3609.js:2:591974)
    at R (https://cdn.registry.platformio.org/static/js/main.88ce3609.js:2:640014)
    at I (https://cdn.registry.platformio.org/static/js/main.88ce3609.js:2:641342)
```

**Comment by ivankravets** [comment]
Please press Ctrl+R in your browser.
