### ISSUE TITLE
[Error] NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.

### ISSUE THREAD

**Issue by SPSArmin** [platformio/platformio-registry#64]
# Page
https://registry.platformio.org/libraries/arduino-libraries/TFT/installation

# Stack
```
at _ (https://cdn.registry.platformio.org/static/js/main.88ce3609.js:2:482003)
    at T (https://cdn.registry.platformio.org/static/js/main.88ce3609.js:2:484635)
    at Suspense
    at div
    at div
    at ee (https://cdn.registry.platformio.org/static/js/main.88ce3609.js:2:190098)
    at div
    at main
    at ne (https://cdn.registry.platformio.org/static/js/main.88ce3609.js:2:192990)
    at _ (https://cdn.registry.platformio.org/static/js/main.88ce3609.js:2:482003)
    at F (https://cdn.registry.platformio.org/static/js/main.88ce3609.js:2:483985)
    at P (https://cdn.registry.platformio.org/static/js/main.88ce3609.js:2:641148)
    at _ (https://cdn.registry.platformio.org/static/js/main.88ce3609.js:2:482003)
    at T (https://cdn.registry.platformio.org/static/js/main.88ce3609.js:2:484635)
    at B (https://cdn.registry.platformio.org/static/js/main.88ce3609.js:2:484048)
    at c (https://cdn.registry.platformio.org/static/js/main.88ce3609.js:2:475312)
    at c.defineProperty.value (https://cdn.registry.platformio.org/static/js/main.88ce3609.js:2:591974)
    at gl (https://cdn.registry.platformio.org/static/js/main.88ce3609.js:2:439587)
    at gl (https://cdn.registry.platformio.org/static/js/main.88ce3609.js:2:439587)
```

**Comment by ivankravets** [comment]
Please press Ctrl+R in your browser. Should be fixed.
