### ISSUE TITLE
[Error] TypeError: Cannot read properties of undefined (reading 'items')

### ISSUE THREAD

**Issue by audreytuffier** [platformio/platformio-registry#67]
# Page
https://registry.platformio.org/libraries/sensirion/Sensirion%20Core/insights/dependents?p=3

# Stack
```
at L (https://cdn.registry.platformio.org/static/js/main.45f52de8.js:2:168877)
    at M (https://cdn.registry.platformio.org/static/js/main.45f52de8.js:2:169728)
    at k (https://cdn.registry.platformio.org/static/js/main.45f52de8.js:2:483711)
    at P (https://cdn.registry.platformio.org/static/js/main.45f52de8.js:2:486343)
    at Suspense
    at div
    at div
    at U (https://cdn.registry.platformio.org/static/js/main.45f52de8.js:2:170194)
    at k (https://cdn.registry.platformio.org/static/js/main.45f52de8.js:2:483711)
    at P (https://cdn.registry.platformio.org/static/js/main.45f52de8.js:2:486343)
    at Suspense
    at div
    at ee (https://cdn.registry.platformio.org/static/js/main.45f52de8.js:2:191434)
    at div
    at main
    at ne (https://cdn.registry.platformio.org/static/js/main.45f52de8.js:2:194326)
    at k (https://cdn.registry.platformio.org/static/js/main.45f52de8.js:2:483711)
    at T (https://cdn.registry.platformio.org/static/js/main.45f52de8.js:2:485693)
    at P (https://cdn.registry.platformio.org/static/js/main.45f52de8.js:2:642655)
    at k (https://cdn.registry.platformio.org/static/js/main.45f52de8.js:2:483711)
    at P (https://cdn.registry.platformio.org/static/js/main.45f52de8.js:2:486343)
    at R (https://cdn.registry.platformio.org/static/js/main.45f52de8.js:2:485756)
    at c (https://cdn.registry.platformio.org/static/js/main.45f52de8.js:2:476816)
    at c.defineProperty.value (https://cdn.registry.platformio.org/static/js/main.45f52de8.js:2:592944)
    at R (https://cdn.registry.platformio.org/static/js/main.45f52de8.js:2:641521)
    at I (https://cdn.registry.platformio.org/static/js/main.45f52de8.js:2:642849)
```

**Comment by ivankravets** [comment]
Thanks for the report! We have fixed it. Please press Ctrl+R in your browser.
