### ISSUE TITLE
[Error] NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.

### ISSUE THREAD

**Issue by lala123jgfyh** [platformio/platformio-registry#71]
# Page
https://registry.platformio.org/libraries/blynkkk/Blynk/installation

# Stack
```
at j (https://cdn.registry.platformio.org/static/js/main.34c13448.js:2:484344)
    at R (https://cdn.registry.platformio.org/static/js/main.34c13448.js:2:487010)
    at Suspense
    at div
    at div
    at ee (https://cdn.registry.platformio.org/static/js/main.34c13448.js:2:191495)
    at div
    at main
    at ne (https://cdn.registry.platformio.org/static/js/main.34c13448.js:2:194387)
    at j (https://cdn.registry.platformio.org/static/js/main.34c13448.js:2:484344)
    at O (https://cdn.registry.platformio.org/static/js/main.34c13448.js:2:486360)
    at P (https://cdn.registry.platformio.org/static/js/main.34c13448.js:2:643931)
    at j (https://cdn.registry.platformio.org/static/js/main.34c13448.js:2:484344)
    at R (https://cdn.registry.platformio.org/static/js/main.34c13448.js:2:487010)
    at B (https://cdn.registry.platformio.org/static/js/main.34c13448.js:2:486423)
    at h (https://cdn.registry.platformio.org/static/js/main.34c13448.js:2:477493)
    at o.defineProperty.value (https://cdn.registry.platformio.org/static/js/main.34c13448.js:2:594096)
    at gl (https://cdn.registry.platformio.org/static/js/main.34c13448.js:2:441638)
    at gl (https://cdn.registry.platformio.org/static/js/main.34c13448.js:2:441638)
```

**Comment by ivankravets** [comment]
Please Ctrl+R and refresh the page.
